[package]
name = "vanity_address_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = "0.21.0" # For key generation
sha3 = "0.10"        # For keccak256 hashing
hex = "0.4"          # For converting bytes to hex strings

