name: Rust

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: rustup update stable
    - name: Build the project
      run: cargo build --release
    - name: Run unit tests
      run: cargo test
